// ============================================================================
// hausdorff_bench.cu -- standalone perf bench for hausdorff_block vs. CoACD CPU.
//
// Compares:
//   host:   face_hausdorff_distance (CoACD CPU, nanoflann KD-tree + P2Tri)
//   device: hausdorff_block (GPU: sampling + linear BVH, 256 threads/block)
//
// Data sets (from hausdorff_data.h, generated by prepare_hausdorff_data.py):
//   Bunny   : mesh  4891 v / 9790 t  vs  hull   320 v / 636 t
//   49160   : mesh   278 v /  552 t  vs  hull    96 v / 188 t
//
// Batch sizes:
//   1   - one HD pair (single block on GPU, single call on CPU)
//   100 - one HD pair replicated (100 blocks on GPU, sequential loop on CPU)
//
// Build (from bench/):
//   make -f Makefile.hausdorff           # default ARCH=89
//   make -f Makefile.hausdorff verbose   # with ptxas -v
// Run:
//   ./hausdorff_bench > results_hausdorff.csv
// ============================================================================

#include <cuda_runtime.h>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

#include "hausdorff.cuh"
#include "common.cuh"
#include "structs.cuh"

// mm.cu is linked separately; forward-declare heap_init_kernel.
extern "C" __global__ void heap_init_kernel(DevicePool* pool);

#include "hausdorff_data.h"

// ============================================================================
// CUDA error check
// ============================================================================
#define CK(expr) do {                                                     \
    cudaError_t _e = (expr);                                              \
    if (_e != cudaSuccess) {                                              \
        std::fprintf(stderr, "CUDA error %s at %s:%d: %s\n",              \
                     cudaGetErrorString(_e), __FILE__, __LINE__, #expr);  \
        std::exit(1);                                                     \
    }                                                                     \
} while (0)

// ============================================================================
// CPU reference (compiled as bench_cpu_hausdorff.cpp; linked with nanoflann).
// ============================================================================
extern "C" double bench_cpu_hausdorff_single(const float* verts_a, const int* tris_a,
                                              int nv_a, int nt_a,
                                              const float* verts_b, const int* tris_b,
                                              int nv_b, int nt_b,
                                              unsigned int resolution,
                                              unsigned int seed);
extern "C" double bench_cpu_hausdorff_batch(const float* verts_a, const int* tris_a,
                                             int nv_a, int nt_a,
                                             const float* verts_b, const int* tris_b,
                                             int nv_b, int nt_b,
                                             int batch,
                                             unsigned int resolution,
                                             unsigned int seed);

// ============================================================================
// Device pool / heap setup (mirrors hull_bench.cu).
// ============================================================================
struct DevPool {
    void*               d_pool_mem   = nullptr;
    unsigned long long* d_pool_off   = nullptr;
    DevicePool*         d_pool       = nullptr;
    size_t              capacity     = 0;
};

static void init_pool(DevPool& p, size_t pool_bytes) {
    CK(cudaMalloc(&p.d_pool_mem, pool_bytes));
    CK(cudaMalloc((void**)&p.d_pool_off, sizeof(unsigned long long)));
    CK(cudaMalloc((void**)&p.d_pool,     sizeof(DevicePool)));
    CK(cudaMemset(p.d_pool, 0, sizeof(DevicePool)));
    p.capacity = pool_bytes;

    DevicePool host_dp{};
    host_dp.base     = (char*)p.d_pool_mem;
    host_dp.offset   = p.d_pool_off;
    host_dp.capacity = (unsigned long long)pool_bytes;
    CK(cudaMemcpy(p.d_pool, &host_dp, offsetof(DevicePool, heap),
                  cudaMemcpyHostToDevice));

    unsigned long long zero = 0;
    CK(cudaMemcpy(p.d_pool_off, &zero, sizeof(zero), cudaMemcpyHostToDevice));
    heap_init_kernel<<<HEAP_NUM_ARENAS * 2, 32>>>(p.d_pool);
    CK(cudaDeviceSynchronize());
}

static void reset_pool_offset(DevPool& p) {
    unsigned long long zero = 0;
    CK(cudaMemcpy(p.d_pool_off, &zero, sizeof(zero), cudaMemcpyHostToDevice));
    heap_init_kernel<<<HEAP_NUM_ARENAS * 2, 32>>>(p.d_pool);
    CK(cudaDeviceSynchronize());
}

static void free_pool(DevPool& p) {
    if (p.d_pool_mem) cudaFree(p.d_pool_mem);
    if (p.d_pool_off) cudaFree(p.d_pool_off);
    if (p.d_pool)     cudaFree(p.d_pool);
    p = {};
}

static inline DeviceHeap* d_heap_ptr(DevPool& p) {
    return (DeviceHeap*)((char*)p.d_pool + offsetof(DevicePool, heap));
}
static inline DeviceHeap* d_scratch_ptr(DevPool& p) {
    return (DeviceHeap*)((char*)p.d_pool + offsetof(DevicePool, scratch));
}

// ============================================================================
// Timing helpers (pristine input restored before each measured run).
// ============================================================================
struct TimingResult {
    double mean_ms;
    double std_ms;
    bool   ok;
};

template<typename SetupFn, typename BodyFn>
TimingResult time_cuda(SetupFn setup, BodyFn body, int warmup, int measure) {
    for (int i = 0; i < warmup; i++) { setup(); body(); }
    CK(cudaDeviceSynchronize());

    cudaEvent_t e0, e1;
    CK(cudaEventCreate(&e0));
    CK(cudaEventCreate(&e1));

    std::vector<double> times(measure);
    for (int i = 0; i < measure; i++) {
        setup();
        CK(cudaEventRecord(e0));
        body();
        CK(cudaEventRecord(e1));
        CK(cudaEventSynchronize(e1));
        CK(cudaGetLastError());
        float ms = 0.f;
        CK(cudaEventElapsedTime(&ms, e0, e1));
        times[i] = ms;
    }
    CK(cudaDeviceSynchronize());
    CK(cudaEventDestroy(e0));
    CK(cudaEventDestroy(e1));

    double m = 0;  for (double t : times) m += t;  m /= measure;
    double v = 0;  for (double t : times) v += (t - m) * (t - m);
    v /= measure;
    return {m, std::sqrt(v), true};
}

template<typename SetupFn, typename BodyFn>
TimingResult time_host(SetupFn setup, BodyFn body, int warmup, int measure) {
    for (int i = 0; i < warmup; i++) { setup(); body(); }
    std::vector<double> times(measure);
    for (int i = 0; i < measure; i++) {
        setup();
        auto t0 = std::chrono::high_resolution_clock::now();
        body();
        auto t1 = std::chrono::high_resolution_clock::now();
        times[i] = std::chrono::duration<double, std::milli>(t1 - t0).count();
    }
    double m = 0;  for (double t : times) m += t;  m /= measure;
    double v = 0;  for (double t : times) v += (t - m) * (t - m);
    v /= measure;
    return {m, std::sqrt(v), true};
}

struct KernelInfo { int regs; int smem; };
static KernelInfo kinfo(const void* f) {
    if (!f) return {-1, -1};
    cudaFuncAttributes a{};
    if (cudaFuncGetAttributes(&a, f) != cudaSuccess) return {-1, -1};
    return {a.numRegs, (int)a.sharedSizeBytes};
}

// ============================================================================
// Row printer
// ============================================================================
static void print_row(const char* algo, const char* dataset,
                      int batch, int nv_a, int nt_a, int nv_b, int nt_b,
                      const TimingResult& r, KernelInfo ki, double mean_dist)
{
    if (!r.ok) {
        std::printf("%s,%s,%d,%d,%d,%d,%d,skip,skip,%d,%d,%.6g\n",
                    algo, dataset, batch, nv_a, nt_a, nv_b, nt_b,
                    ki.regs, ki.smem, mean_dist);
    } else {
        std::printf("%s,%s,%d,%d,%d,%d,%d,%.4f,%.4f,%d,%d,%.6g\n",
                    algo, dataset, batch, nv_a, nt_a, nv_b, nt_b,
                    r.mean_ms, r.std_ms, ki.regs, ki.smem, mean_dist);
    }
    std::fflush(stdout);
}

// ============================================================================
// Device-side mesh builder: copy flat host arrays into device heap.
// ============================================================================
static Mesh upload_mesh(const float* h_verts, int nv,
                        const int*   h_tris,  int nt,
                        DeviceHeap*  heap,
                        int*         kernel_error)
{
    Mesh m{};
    m.nv = nv;
    m.nt = nt;

    // Single allocation to hold verts + tris + refcount int
    size_t verts_sz = (size_t)nv * 3 * sizeof(float);
    size_t tris_sz  = (size_t)nt * 3 * sizeof(int);
    size_t ref_sz   = sizeof(int);
    size_t total    = verts_sz + tris_sz + ref_sz;

    void* p = nullptr;
    // heap_alloc is __device__ only -- use cudaMalloc for benchmark simplicity.
    CK(cudaMalloc(&p, total));
    m.verts = (float*)p;
    m.tris  = (int*)((char*)p + verts_sz);
    m.refcount = (int*)((char*)p + verts_sz + tris_sz);

    CK(cudaMemcpy(m.verts, h_verts, verts_sz, cudaMemcpyHostToDevice));
    CK(cudaMemcpy(m.tris,  h_tris,  tris_sz,  cudaMemcpyHostToDevice));
    CK(cudaMemset(m.refcount, 0, ref_sz));

    (void)heap; (void)kernel_error; // heap unused here -- we cudaMalloc separately.
    return m;
}

static void free_mesh(Mesh& m) {
    if (m.verts) {
        // Single cudaMalloc block for verts+tris+refcount.
        cudaFree(m.verts);
        m.verts = nullptr;
        m.tris  = nullptr;
        m.refcount = nullptr;
    }
}

// ============================================================================
// GPU kernel wrapper (one block per Hausdorff pair, 256 threads).
// ============================================================================
extern "C" __global__ void bench_hausdorff_kernel(
    const Mesh* __restrict__ meshes_a,
    const Mesh* __restrict__ meshes_b,
    int          n_pairs,
    DeviceHeap*  scratch_heap,
    int*         out_errors,
    float*       out_results)
{
    int bid = blockIdx.x;
    if (bid >= n_pairs) return;

    // Each block needs a local copy of Mesh because hausdorff_block
    // is __device__ and takes Mesh* (it reads .verts, .tris, .nv, .nt).
    Mesh ma = meshes_a[bid];
    Mesh mb = meshes_b[bid];
    int err = 0;
    float d = hausdorff_block(&ma, &mb, scratch_heap, &err);
    if (threadIdx.x == 0) {
        out_results[bid] = d;
        out_errors[bid]  = err;
    }
}

// ============================================================================
// One case: (dataset, batch). Runs CPU and GPU.
// ============================================================================
static constexpr int CUDA_WARMUP  = 2;
static constexpr int CUDA_MEASURE = 5;
static constexpr int HOST_WARMUP  = 1;
static constexpr int HOST_MEASURE = 3;

static void run_case(const char* dataset_name,
                     const float* verts_a, const int* tris_a, int nv_a, int nt_a,
                     const float* verts_b, const int* tris_b, int nv_b, int nt_b,
                     int batch, DevPool& pool)
{
    // -------------------------------------------------------------------- CPU
    {
        double mean_dist = 0.0;
        auto setup = [&] {};
        auto body  = [&] {
            if (batch == 1) {
                mean_dist = bench_cpu_hausdorff_single(
                    verts_a, tris_a, nv_a, nt_a,
                    verts_b, tris_b, nv_b, nt_b,
                    2000, 1234);
            } else {
                mean_dist = bench_cpu_hausdorff_batch(
                    verts_a, tris_a, nv_a, nt_a,
                    verts_b, tris_b, nv_b, nt_b,
                    batch, 2000, 1234);
            }
        };
        TimingResult r = time_host(setup, body, HOST_WARMUP, HOST_MEASURE);
        print_row("cpu_coacd_hd", dataset_name, batch,
                  nv_a, nt_a, nv_b, nt_b, r, {-1, -1}, mean_dist);
    }

    // -------------------------------------------------------------------- GPU
    // Upload two meshes (single base mesh, single hull).
    DeviceHeap* d_sc = d_scratch_ptr(pool);
    int h_err = 0;
    int* d_err = nullptr;
    float* d_results = nullptr;

    // For batch > 1 we replicate the same mesh pair n times.
    std::vector<Mesh> h_meshes_a(batch);
    std::vector<Mesh> h_meshes_b(batch);
    for (int i = 0; i < batch; ++i) {
        h_meshes_a[i] = upload_mesh(verts_a, nv_a, tris_a, nt_a, d_sc, &h_err);
        h_meshes_b[i] = upload_mesh(verts_b, nv_b, tris_b, nt_b, d_sc, &h_err);
    }

    Mesh* d_meshes_a = nullptr;
    Mesh* d_meshes_b = nullptr;
    CK(cudaMalloc(&d_meshes_a, (size_t)batch * sizeof(Mesh)));
    CK(cudaMalloc(&d_meshes_b, (size_t)batch * sizeof(Mesh)));
    CK(cudaMalloc(&d_err,      (size_t)batch * sizeof(int)));
    CK(cudaMalloc(&d_results,  (size_t)batch * sizeof(float)));
    CK(cudaMemcpy(d_meshes_a, h_meshes_a.data(), (size_t)batch * sizeof(Mesh), cudaMemcpyHostToDevice));
    CK(cudaMemcpy(d_meshes_b, h_meshes_b.data(), (size_t)batch * sizeof(Mesh), cudaMemcpyHostToDevice));
    CK(cudaMemset(d_err, 0, (size_t)batch * sizeof(int)));
    CK(cudaMemset(d_results, 0, (size_t)batch * sizeof(float)));

    auto setup = [&] { reset_pool_offset(pool); };
    auto body  = [&] {
        bench_hausdorff_kernel<<<batch, HD_BLOCK>>>(
            d_meshes_a, d_meshes_b, batch, d_sc, d_err, d_results);
    };
    TimingResult r = time_cuda(setup, body, CUDA_WARMUP, CUDA_MEASURE);

    // Read back one result to verify.
    float h_res = 0.f;
    CK(cudaMemcpy(&h_res, d_results, sizeof(float), cudaMemcpyDeviceToHost));
    int h_err0 = 0;
    CK(cudaMemcpy(&h_err0, d_err, sizeof(int), cudaMemcpyDeviceToHost));

    KernelInfo ki = kinfo((const void*)bench_hausdorff_kernel);
    double dist = (h_err0 == 0) ? static_cast<double>(h_res) : 0.0;
    print_row("hausdorff_block", dataset_name, batch,
              nv_a, nt_a, nv_b, nt_b, r, ki, dist);

    // Cleanup.
    cudaFree(d_meshes_a);
    cudaFree(d_meshes_b);
    cudaFree(d_err);
    cudaFree(d_results);
    for (int i = 0; i < batch; ++i) {
        free_mesh(h_meshes_a[i]);
        free_mesh(h_meshes_b[i]);
    }
}

// ============================================================================
// Main
// ============================================================================
int main(int argc, char** argv) {
    int device = 0;
    for (int i = 1; i < argc; i++) {
        if (std::strcmp(argv[i], "--device") == 0 && i + 1 < argc)
            device = std::atoi(argv[++i]);
    }
    CK(cudaSetDevice(device));
    CK(cudaDeviceSetLimit(cudaLimitStackSize, 8 * 1024));

    DevPool pool;
    init_pool(pool, (size_t)2 * 1024 * 1024 * 1024);   // 2 GB

    std::printf("algorithm,dataset,batch,nv_a,nt_a,nv_b,nt_b,mean_ms,std_ms,regs,smem,mean_dist\n");

    // Bunny: mesh 4891v/9790t vs hull 320v/636t
    run_case("bunny",
             BUNNY_VERTS, BUNNY_TRIS, BUNNY_NV, BUNNY_NT,
             BUNNY_HULL_VERTS, BUNNY_HULL_TRIS, BUNNY_HULL_NV, BUNNY_HULL_NT,
             1, pool);
    run_case("bunny",
             BUNNY_VERTS, BUNNY_TRIS, BUNNY_NV, BUNNY_NT,
             BUNNY_HULL_VERTS, BUNNY_HULL_TRIS, BUNNY_HULL_NV, BUNNY_HULL_NT,
             100, pool);

    // 49160: mesh 278v/552t vs hull 96v/188t
    run_case("49160",
             STL_VERTS, STL_TRIS, STL_NV, STL_NT,
             STL_HULL_VERTS, STL_HULL_TRIS, STL_HULL_NV, STL_HULL_NT,
             1, pool);
    run_case("49160",
             STL_VERTS, STL_TRIS, STL_NV, STL_NT,
             STL_HULL_VERTS, STL_HULL_TRIS, STL_HULL_NV, STL_HULL_NT,
             100, pool);

    free_pool(pool);
    return 0;
}
