#!/usr/bin/env python3
"""Prepare mesh + hull data as a C header for hausdorff_bench.cu.

Loads bunny.obj and 49160.stl, computes convex hulls with trimesh,
and writes bench/hausdorff_data.h with float/int arrays.
"""

import numpy as np
import trimesh
import os


def normalize(m: trimesh.Trimesh):
    """Center mesh and scale to [-1, 1], matching test_lookahead."""
    verts = np.asarray(m.vertices, dtype=np.float32)
    lo = verts.min(axis=0)
    hi = verts.max(axis=0)
    center = (lo + hi) / 2.0
    extent = (hi - lo).max()
    scale = extent / 2.0 if extent > 0 else 1.0
    verts = (verts - center) / scale
    m.vertices = verts
    return m


def mesh_data(m: trimesh.Trimesh):
    verts = m.vertices.astype(np.float32).flatten()
    faces = m.faces.astype(np.int32).flatten()
    return verts, faces, len(m.vertices), len(m.faces)


def emit_array(name, arr):
    vals = ", ".join(str(v) for v in arr)
    return f"static const float {name}[] = {{ {vals} }};"


def emit_array_int(name, arr):
    vals = ", ".join(str(v) for v in arr)
    return f"static const int {name}[] = {{ {vals} }};"


def main():
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    entries = []
    for path_key, mesh_path in [
        ("BUNNY", "tests/data/vhacd/bunny.obj"),
        ("STL",   "tests/data/49160.stl"),
    ]:
        full = os.path.join(repo, mesh_path)
        m = normalize(trimesh.load_mesh(full, force="mesh"))
        h = normalize(m.convex_hull)

        mv, mf, mnv, mnt = mesh_data(m)
        hv, hf, hnv, hnt = mesh_data(h)

        entries.append(f"// {path_key}: mesh {mesh_path}")
        entries.append(emit_array(f"{path_key}_VERTS", mv))
        entries.append(emit_array_int(f"{path_key}_TRIS", mf))
        entries.append(f"static const int {path_key}_NV = {mnv};")
        entries.append(f"static const int {path_key}_NT = {mnt};")
        entries.append(emit_array(f"{path_key}_HULL_VERTS", hv))
        entries.append(emit_array_int(f"{path_key}_HULL_TRIS", hf))
        entries.append(f"static const int {path_key}_HULL_NV = {hnv};")
        entries.append(f"static const int {path_key}_HULL_NT = {hnt};")
        entries.append("")

    header = os.path.join(repo, "bench", "hausdorff_data.h")
    with open(header, "w") as f:
        f.write("// Auto-generated by prepare_hausdorff_data.py\n")
        f.write("#pragma once\n\n")
        f.write("\n".join(entries))
    print(f"Wrote {header}")


if __name__ == "__main__":
    main()
