name: Build wheels

on:
  workflow_dispatch:

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS: auto64
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_ALL_LINUX: bash ci/setup_manylinux.sh
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BUILD: cp310-*
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: >-
            pip install -U auditwheel patchelf &&
            auditwheel repair -w {dest_dir} {wheel} --exclude libcuda.so.1
          CIBW_ENVIRONMENT: "CUDA_HOME=/usr/local/cuda CUACD_GPU_ARCHS=80;86;89;90"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
